export const colors = {
  orange: '#F97316',
  orangeHover: '#EA580C',
  orangeLight: '#FFF7ED',
  orangeBorder: '#FDBA74',
  bg: '#FAFAFA',
  card: '#FFFFFF',
  text: '#1F2937',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  border: '#E5E7EB',
  error: '#DC2626',
  errorBg: '#FEF2F2',
  success: '#16A34A',
  successBg: '#F0FDF4',
};

export const shared = {
  page: {
    minHeight: '100vh',
    backgroundColor: colors.bg,
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    color: colors.text,
  } as React.CSSProperties,
  container: {
    maxWidth: 560,
    margin: '0 auto',
    padding: '40px 24px',
  } as React.CSSProperties,
  card: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: '32px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
    border: `1px solid ${colors.border}`,
  } as React.CSSProperties,
  title: {
    fontSize: '1.75rem',
    fontWeight: 700,
    margin: '0 0 8px',
    color: colors.text,
  } as React.CSSProperties,
  subtitle: {
    fontSize: '1rem',
    color: colors.textSecondary,
    margin: '0 0 24px',
    lineHeight: 1.5,
  } as React.CSSProperties,
  label: {
    display: 'block',
    marginBottom: 6,
    fontWeight: 500,
    fontSize: '0.875rem',
    color: colors.text,
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '10px 14px',
    fontSize: '1rem',
    border: `1px solid ${colors.border}`,
    borderRadius: 10,
    boxSizing: 'border-box' as const,
    outline: 'none',
    transition: 'border-color 0.15s',
    backgroundColor: '#fff',
  } as React.CSSProperties,
  inputError: {
    borderColor: colors.error,
  } as React.CSSProperties,
  btn: {
    padding: '10px 24px',
    fontSize: '1rem',
    fontWeight: 600,
    border: 'none',
    borderRadius: 10,
    backgroundColor: colors.orange,
    color: '#fff',
    cursor: 'pointer',
    transition: 'background-color 0.15s',
  } as React.CSSProperties,
  btnOutline: {
    padding: '10px 24px',
    fontSize: '1rem',
    fontWeight: 500,
    border: `1.5px solid ${colors.orange}`,
    borderRadius: 10,
    backgroundColor: 'transparent',
    color: colors.orange,
    cursor: 'pointer',
    transition: 'all 0.15s',
  } as React.CSSProperties,
  btnDisabled: {
    opacity: 0.55,
    cursor: 'not-allowed',
  } as React.CSSProperties,
  errorBox: {
    padding: '10px 14px',
    marginBottom: 16,
    borderRadius: 10,
    backgroundColor: colors.errorBg,
    color: colors.error,
    fontSize: '0.875rem',
  } as React.CSSProperties,
  fieldError: {
    color: colors.error,
    margin: '4px 0 0',
    fontSize: '0.8rem',
  } as React.CSSProperties,
  logo: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: colors.orange,
    marginBottom: 24,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  } as React.CSSProperties,
};
