ALTER TABLE event ADD COLUMN location_city VARCHAR(255);
ALTER TABLE event ADD COLUMN location_country VARCHAR(10);
ALTER TABLE event ADD COLUMN location_lat DOUBLE PRECISION;
ALTER TABLE event ADD COLUMN location_lng DOUBLE PRECISION;
