import { Link } from 'react-router-dom';
import { getCurrentUserId } from '../api/client';

export default function TermsOfService() {
  const userId = getCurrentUserId();
  return (
    <div className="gf-stack gf-stack--xl" style={{ padding: '20px 0 60px' }}>
      <Link
        to={userId ? '/dashboard' : '/'}
        className="gf-button gf-button--ghost gf-button--sm"
        style={{ alignSelf: 'flex-start' }}
      >
        ← Back
      </Link>
      <div>
        <h1 className="gf-section-title">Terms of Service</h1>
        <p className="gf-muted">Last updated: March 22, 2026</p>
      </div>
      <div
        className="gf-card"
        style={{ display: 'flex', flexDirection: 'column', gap: '16px', lineHeight: '1.6' }}
      >
        <p>
          Welcome to Go Fish. By accessing or using our application, you agree to be bound by these
          Terms of Service. If you do not agree to these terms, please do not use our platform.
        </p>

        <h3 className="gf-card-title">1. Description of Service</h3>
        <p>
          Go Fish is a social event coordination platform that collects group availability and uses
          artificial intelligence to suggest tailored group activities. The service includes event
          creation, invitation management, and automated activity generation.
        </p>

        <h3 className="gf-card-title">2. AI-Generated Content</h3>
        <p>
          Our activity suggestions are generated by third-party artificial intelligence (Google
          Gemini).{' '}
          <strong>
            We do not guarantee the accuracy, availability, pricing, safety, or quality of any
            suggested venues or activities.
          </strong>{' '}
          Users are strictly responsible for verifying venue details, operating hours, and booking
          requirements independently before attending.
        </p>

        <h3 className="gf-card-title">3. User Conduct</h3>
        <p>
          You agree to use Go Fish only for lawful purposes. You are solely responsible for the
          content of your event descriptions and communications. You agree not to use the service to
          organize illegal activities, harass others, or submit abusive content.
        </p>

        <h3 className="gf-card-title">4. Limitation of Liability</h3>
        <p>
          Go Fish is provided on an "as is" and "as available" basis. To the maximum extent
          permitted by law, Go Fish and its creators shall not be liable for any direct, indirect,
          incidental, or consequential damages resulting from your use of the service.{' '}
          <strong>
            Participation in any physical activities or visits to venues suggested by the
            application is entirely at your own risk.
          </strong>
        </p>

        <h3 className="gf-card-title">5. Account Termination</h3>
        <p>
          We reserve the right to suspend or terminate your account and access to the service at our
          sole discretion, without notice, for conduct that we believe violates these Terms of
          Service or is harmful to other users of the application.
        </p>
      </div>
    </div>
  );
}
